apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-envoy
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
    - name: blue
      port: 8080
      targetPort: blue
    - name: green
      port: 8081
      targetPort: green
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-externalname-blue
spec:
  type: ExternalName
  externalName: hello-kubernetes-v1.hello-kubernetes-blue.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-externalname-green
spec:
  type: ExternalName
  externalName: hello-kubernetes-v2.hello-kubernetes-green.svc.cluster.local
