apiVersion: v1
kind: Service
metadata:
  name: webserver

spec: # Service Spec
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

  selector: # select pod
    app: photo-view
