apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memoryleak
spec:
  maxReplicas: 12
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memoryleak
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 30
          type: Utilization
  behavior:
    scaleDown: # scale down gradually every 30sec with 20%
      stabilizationWindowSeconds: 60 # default 300sec. Shorten window seconds may result to unstable pod number of scaling.
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
